<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
	<LangVersion>12</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RockWebPath>..\..\Rock\RockWeb</RockWebPath>
    <AdditionalAssembliesToCopy></AdditionalAssembliesToCopy>
    <CopyToRockWeb>true</CopyToRockWeb>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SparkDevNetwork.Rock.Build.Tasks" Version="1.0.7" />
    <PackageReference Include="SparkDevNetwork.Rock.Analyzers" Version="1.0.7" />
    <PackageReference Include="RockRMS.Rock" Version="19.1.8" />
    <PackageReference Include="RockRMS.Rock.Blocks" Version="19.1.8" />
  </ItemGroup>

</Project>
